// Auto-generated form card data for 31 races
export const formData = {
  "Alice Springs": {
    "1": {
      "1": "Hydrobomb",
      "2": "Am I Dreaming",
      "3": "Diameter",
      "4": "Don'T Look Back",
      "5": "Stitzer",
      "6": "Salann",
      "7": "Farcolo",
      "8": "Sumac",
      "9": "Tiger Turf",
      "10": "To Dubai We Go",
      "11": "Universe"
    },
    "2": {
      "1": "Beskar",
      "2": "Within The Law",
      "3": "State Visit",
      "4": "Regal Award",
      "5": "Grand Prairie",
      "6": "Burma Star",
      "7": "Options",
      "8": "Mareth",
      "9": "Azarax",
      "10": "Samarelle",
      "11": "Autumn King",
      "12": "Cavallo Park",
      "13": "Eleven X",
      "14": "Probability Theory",
      "15": "Siragusa"
    },
    "3": {
      "1": "Medicinal",
      "2": "Satono Glow",
      "3": "Lumbini",
      "4": "Screen Icon",
      "5": "Ciaron's Star",
      "6": "Cherry Bomshell",
      "7": "Rachini",
      "8": "She's Extra",
      "9": "Reachin' Out"
    },
    "4": {
      "1": "Lord Of Biscay",
      "2": "Midnight Opal",
      "3": "Il Passero",
      "4": "Mogul Monarch",
      "5": "Matcha Latte",
      "6": "Buffalo",
      "7": "Octa De Lago",
      "8": "Oui Oui Oui",
      "9": "Imposant",
      "10": "Oakfield Jupiter",
      "11": "Flying Embers",
      "12": "Miss Busslinger",
      "13": "Miss Spacegirl",
      "14": "Harry'S Bar",
      "15": "Oakfield Saturn",
      "16": "Mailata",
      "17": "Strawberry Impact"
    },
    "5": {
      "1": "Ohope Wins",
      "2": "After Summer",
      "3": "Profoundly",
      "4": "Soverato",
      "5": "Long Legs",
      "6": "Stand My Ground",
      "7": "Classic Gem",
      "8": "Queen Of Clubs",
      "9": "Satono Invader",
      "10": "La Morra",
      "11": "Mountain Queen",
      "12": "Dance With Destiny"
    },
    "6": {
      "1": "Beiwacht",
      "2": "Devil Night",
      "3": "Grafterburners",
      "4": "Skyhook",
      "5": "Pallaton",
      "6": "Beadman",
      "7": "Nashville Jack",
      "8": "Marhoona",
      "9": "Tempted",
      "10": "Caffe Florian"
    },
    "7": {
      "1": "River Of Stars",
      "2": "Campaldino",
      "3": "Changingoftheguard",
      "4": "Soul Of Spain",
      "5": "Whisky On The Hill",
      "6": "Valiant King",
      "7": "Paradise Storm",
      "8": "Piggyback",
      "9": "Athabascan",
      "10": "Juja Kibo",
      "11": "Mr Monaco",
      "12": "Machine Gun Gracie",
      "13": "Newlook",
      "14": "Litzdeel",
      "15": "Highland Bling",
      "16": "Hutchence"
    }
  },
  "Ascot": {
    "1": {
      "1": "Pride Of Jenni",
      "2": "Lady Shenandoah",
      "3": "Treasurethe Moment",
      "4": "Lazzura",
      "5": "She'S A Hustler",
      "6": "Leica Lucy",
      "7": "Arctic Glamour",
      "8": "Idle Flyer",
      "9": "Melody Again",
      "10": "Pinito",
      "11": "Perfumist",
      "12": "Dark Glitter",
      "13": "Modella",
      "14": "Ole Dancer"
    },
    "2": {
      "1": "Dubai Honour",
      "2": "Sir Delius",
      "3": "Light Infantry Man",
      "4": "Lindermann",
      "5": "Wootton Verni",
      "6": "Caviar Heights",
      "7": "Autumn Glow",
      "8": "Aeliana"
    },
    "3": {
      "1": "Splash Back",
      "2": "Infancy",
      "3": "Gangsta Granny",
      "4": "Catch The Glory",
      "5": "In Flight",
      "6": "Flying For Fun",
      "7": "Coco Jamboo",
      "8": "She'S Got Pizzazz",
      "9": "Tiger Shark",
      "10": "Monte Supreme",
      "11": "More Territories",
      "12": "Spring Lee",
      "13": "Monte Kate",
      "14": "Husk"
    },
    "4": {
      "1": "Super Sharp",
      "3": "Frawley",
      "4": "Verbosity",
      "5": "Daniher",
      "6": "Pompeii Empire",
      "7": "Grinzinger Lass",
      "8": "Limited Risk",
      "9": "Mods"
    },
    "5": {
      "1": "The Final Word",
      "2": "Kieffer",
      "3": "Hebel",
      "4": "Lean On Me",
      "5": "Lucky Fortuna",
      "6": "Stella Bystarlight",
      "7": "Dolce D'Amour",
      "8": "Mr Jones",
      "9": "Peace Baby"
    },
    "6": {
      "1": "Highlands",
      "2": "Black Coal",
      "3": "Bon'S A Lad",
      "4": "Pub Crawl",
      "5": "Our Squamosa",
      "6": "Standard Street",
      "7": "Bad Man",
      "8": "Boomerconi"
    },
    "7": {
      "1": "Flying Yishu",
      "2": "O'Tycoon",
      "3": "Rewards And More",
      "4": "Delago Lad",
      "5": "Rock Of Kryptonite",
      "6": "Equal Balance",
      "7": "Mathematics"
    },
    "8": {
      "1": "Chief White Sock",
      "2": "Dad Bod",
      "3": "Boss Shelby",
      "4": "Rosebud Lass",
      "5": "Arrogant Miss",
      "6": "Sha Na Na",
      "7": "Taormina Duchess",
      "8": "Valabing",
      "9": "Game Cove"
    },
    "9": {
      "1": "Miracoli",
      "3": "Valley Prince",
      "4": "Ourania",
      "5": "Mummsie",
      "6": "Becquerel",
      "7": "Nasha",
      "8": "Qualis",
      "9": "Denuto"
    },
    "10": {
      "1": "Active Duty",
      "2": "Valimi",
      "3": "Our Couver",
      "4": "Venting",
      "5": "Princess Pancakes",
      "6": "Matron Samsing",
      "7": "Enterprise Lassie",
      "8": "Figo The Great"
    }
  },
  "Ballina": {
    "1": {
      "1": "Harry",
      "2": "Territory Style",
      "3": "Snow Dog",
      "4": "Hard Choice",
      "5": "Yasena",
      "6": "Raygun Rocks",
      "7": "Ally Alley Ali",
      "8": "Blazing Courage",
      "9": "By Linda",
      "10": "Finest Art",
      "11": "Kneel Down"
    },
    "2": {
      "1": "Casterly Rock",
      "2": "Himeros",
      "3": "The Bentley",
      "4": "Dark Thinker",
      "5": "Frosty The Showman",
      "6": "Majestic Roca",
      "7": "Burning Ambition",
      "8": "Forwarding",
      "9": "Show Us Ya Texts",
      "10": "Sixteen Straight"
    },
    "3": {
      "1": "Deel Head",
      "2": "The Glen",
      "3": "Fuel The Jet",
      "4": "Heeza Steve",
      "5": "Tiara Gaga",
      "6": "Zippy Lion",
      "7": "Passing Through",
      "8": "Raining Violets",
      "9": "Extremely Exciting",
      "10": "Mr Usher",
      "11": "Suspicious Time",
      "12": "Whymsical Spirit",
      "13": "Yesglenn",
      "14": "Zo Frilling",
      "15": "Prince De Vega"
    },
    "4": {
      "1": "Crepescule",
      "2": "Missile Defence",
      "3": "Tjaka",
      "4": "Maralago",
      "5": "Performing Diva",
      "6": "Cheap Shot",
      "7": "Flats",
      "8": "Lucilago",
      "9": "Tillman",
      "10": "Jacob Joe",
      "11": "The Pres",
      "12": "Kisses For Jody"
    },
    "5": {
      "1": "Stormy Woo",
      "2": "Hellfire Henry",
      "3": "Maxis Legacy",
      "4": "Prince De Vega",
      "5": "The Hard Road",
      "6": "Second Deb",
      "7": "Chance To Shine",
      "8": "Elasand",
      "9": "Gong Girl",
      "10": "Inspiritu",
      "11": "Mamma Mia",
      "12": "Manzobeel",
      "13": "Sunset Royale",
      "14": "Too Her Core",
      "15": "On The Fly",
      "16": "King'S Exceed",
      "17": "Amire Waters",
      "18": "Get Litt",
      "19": "Deel Head",
      "20": "Extremely Exciting"
    },
    "6": {
      "1": "Off Shaw",
      "2": "Drama Dodger",
      "3": "Hold",
      "4": "Royalify",
      "5": "Boom In The Dark",
      "6": "Crucial Witness",
      "7": "Blue Dane",
      "8": "Milly Molly Mandy",
      "9": "One More Bout",
      "10": "Tango On",
      "11": "Uber In",
      "12": "Exothrill",
      "13": "Performing Diva",
      "14": "Royal Memory",
      "15": "She'S The Key"
    }
  },
  "Bowen": {
    "1": {
      "1": "Stellar Legend",
      "2": "Zemoreya",
      "3": "Arancia",
      "4": "Missin' De Quo",
      "5": "She'S Got Lyrics",
      "6": "Streamelot"
    },
    "2": {
      "1": "Silver City",
      "2": "War Council",
      "3": "Remlap Kava",
      "4": "Fools Play",
      "5": "Ginger Mick",
      "6": "King Canute",
      "7": "Goncalo"
    },
    "3": {
      "1": "Silver City",
      "2": "Redlights On",
      "3": "Yorokobi",
      "4": "Dubawi'S Girl",
      "5": "Our Missile",
      "6": "Chalkley",
      "7": "Mishani Perfection",
      "8": "The Kobay Train",
      "9": "Egzakly"
    },
    "4": {
      "1": "Hellish",
      "2": "Booming Lad",
      "3": "Under The Limit",
      "4": "Your Too Good",
      "5": "Midas Star",
      "6": "Medal",
      "7": "Raetihi",
      "8": "Snitzaroo"
    },
    "5": {
      "1": "Nolan",
      "2": "Remember Roy",
      "3": "Office Politics",
      "4": "Pro Forma",
      "5": "Capicella",
      "6": "Madam Borodina",
      "7": "Better Not Forget",
      "8": "Secret Boom",
      "9": "Red Hot Lizzie"
    }
  },
  "Caulfield": {
    "1": {
      "1": "My Brothers Keeper",
      "2": "Bring Forth",
      "3": "Bluestone",
      "4": "Jareth",
      "5": "House Of Lords",
      "6": "All So Clear",
      "7": "Merchant Flyer",
      "8": "Almairac",
      "9": "Staunch",
      "10": "Straand Deal",
      "11": "Mr Bannock",
      "12": "En Flique",
      "13": "Aura"
    },
    "2": {
      "1": "He'Ll Rip",
      "2": "Ka Ying Cheer",
      "3": "Greatham Boy",
      "4": "Epimeles",
      "5": "Winsome Star",
      "6": "Wolfy",
      "7": "Shaime",
      "8": "Zemgrinda",
      "9": "Zethus",
      "10": "Prevailed",
      "11": "Foxenberg",
      "12": "King Tut",
      "13": "Boltsaver",
      "14": "Kyle",
      "15": "Volatile"
    }
  },
  "Geraldton": {
    "1": {
      "1": "Mahoney's Machine",
      "2": "Triple Ar",
      "3": "Dixie Princess",
      "4": "Loona Dawn",
      "5": "Boutique Session",
      "6": "Flaming Ronda",
      "7": "Sneaky Session",
      "8": "Diamas"
    }
  }
};